name: sn_tourism
description: "A simple tourism app powered by a local JSON file.."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/tourisme.json
